---
- name: Enable the workshops catalog
  hosts: localhost
  vars:
    definition_file: configmap.yaml.j2
    destination: /usr/share/ansible/openshift-ansible/roles/ansible_service_broker/templates/test-configmap.yaml.j2
  become: false

  tasks:

    - name: set our variables from environment varabiles preset
      set_fact:
        guid: "{{lookup('env','GUID') }}" 
        basesuffix: "{{lookup('env','BASESUFFIX') }}"
    - name: establish target host
      set_fact:
        bastion_host: bastion.{{guid}}.basesuffix
    - debug:
        var: bastion_host

    - name: insert the workshop into the catalog file
      become: True
      copy:
        src: "{{definition_file}}"
        dest: "{{destination}}"
      delegate_to: "{{bastion_host}}"

#     - name: kick off the catalog update
#       become: True
#       shell: ansible-playbook -i /etc/ansible/hosts /usr/share/ansible/openshift-ansible/playbooks/openshift-service-catalog/config.yml 
#       delegate_to: "{{bastion_host}}"
        
